export const CREATE_BUSINESS_FORM_REQUEST = 'CREATE_BUSINESS_FORM_REQUEST';
export const CREATE_BUSINESS_FORM_SUCCESS = 'CREATE_BUSINESS_FORM_SUCCESS';
export const CREATE_BUSINESS_FORM_FAIL = 'CREATE_BUSINESS_FORM_FAIL';

export const BUSINESS_FORM_DETAILS_REQUEST = 'BUSINESS_FORM_DETAILS_REQUEST';
export const BUSINESS_FORM_DETAILS_SUCCESS = 'BUSINESS_FORM_DETAILS_SUCCESS';
export const BUSINESS_FORM_DETAILS_FAIL = 'BUSINESS_FORM_DETAILS_FAIL';

export const BUSINESS_FORM_LIST_REQUEST = 'BUSINESS_FORM_LIST_REQUEST';
export const BUSINESS_FORM_LIST_SUCCESS = 'BUSINESS_FORM_LIST_SUCCESS';
export const BUSINESS_FORM_LIST_FAIL = 'BUSINESS_FORM_LIST_FAIL';

export const BUSINESS_FORM_UPDATE_REQUEST = 'BUSINESS_FORM_UPDATE_REQUEST';
export const BUSINESS_FORM_UPDATE_SUCCESS = 'BUSINESS_FORM_UPDATE_SUCCESS';
export const BUSINESS_FORM_UPDATE_FAIL = 'BUSINESS_FORM_UPDATE_FAIL';

export const FORMATIONDOC_FORM_DETAILS_REQUEST =
  'FORMATIONDOC_FORM_DETAILS_REQUEST';
export const FORMATIONDOC_FORM_DETAILS_SUCCESS =
  'FORMATIONDOC_FORM_DETAILS_SUCCESS';
export const FORMATIONDOC_FORM_DETAILS_FAIL = 'FORMATIONDOC_FORM_DETAILS_FAIL';

export const FORMATIONDOC_FORM_LIST_REQUEST = 'FORMATIONDOC_FORM_LIST_REQUEST';
export const FORMATIONDOC_FORM_LIST_SUCCESS = 'FORMATIONDOC_FORM_LIST_SUCCESS';
export const FORMATIONDOC_FORM_LIST_FAIL = 'FORMATIONDOC_FORM_LIST_FAIL';

export const CREATE_FORMATIONDOC_FORM_REQUEST =
  'CREATE_FORMATIONDOC_FORM_REQUEST';
export const CREATE_FORMATIONDOC_FORM_SUCCESS =
  'CREATE_FORMATIONDOC_FORM_SUCCESS';
export const FORMATIONDOC_FORM_FAIL = 'CREATE_FORMATIONDOC_FORM_FAIL';

export const FORMATIONDOC_FORM_UPDATE_REQUEST =
  'FORMATIONDOC_FORM_UPDATE_REQUEST';
export const FORMATIONDOC_FORM_UPDATE_SUCCESS =
  'FORMATIONDOC_FORM_UPDATE_SUCCESS';
export const FORMATIONDOC_FORM_UPDATE_FAIL = 'FORMATIONDOC_FORM_LIST_FAIL';
