export const CREATE_FORM_REQUEST = 'CREATE_FORM_REQUEST';
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS';
export const CREATE_FORM_FAIL = 'CREATE_FORM_FAIL';

export const FORM_DETAILS_REQUEST = 'FORM_DETAILS_REQUEST';
export const FORM_DETAILS_SUCCESS = 'FORM_DETAILS_SUCCESS';
export const FORM_DETAILS_FAIL = 'FORM_DETAILS_FAIL';
export const FORM_DETAILS_RESET = 'FORM_DETAILS_RESET';

export const FORM_LIST_REQUEST = 'FORM_LIST_REQUEST';
export const FORM_LIST_SUCCESS = 'FORM_LIST_SUCCESS';
export const FORM_LIST_FAIL = 'FORM_LIST_FAIL';

export const FORM_UPDATE_REQUEST = 'FORM_UPDATE_REQUEST';
export const FORM_UPDATE_SUCCESS = 'FORM_UPDATE_SUCCESS';
export const FORM_UPDATE_FAIL = 'FORM_UPDATE_FAIL';
